@hostname = http://localhost:3000
@accestToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5YjQxMTRkMS04MDUzLTQxMjItODA5Yy1jZjNjNWJhZWEzNDMiLCJlbWFpbCI6ImFiY0BnbWFpbC5jb20iLCJwcml2aWxlZ2VzIjpudWxsLCJpYXQiOjE3MTE0NzYxOTksImV4cCI6MTcxMTU2MjU5OX0.PQr6zzWTFNEljxbzSuHY2qJZ750_aaYij3gYWPJqj5U


### Get all household-device
GET  {{hostname}}/household-device
content-type: application/json
Authorization: Bearer {{accestToken}}



### create household-device
POST   {{hostname}}/household-device
content-type: application/json
Authorization: Bearer {{accestToken}}


{
  "name":"cảm biến DHT11 đặt tại ban công",
  "status":true,
  "value":{
    "temperature":26,
    "humidity":67
  },
  "pins_usage":{
    "VCC":"D4"
  },
  "project_id":"c8389c70-25f6-4661-9011-66bb00766050"
}